services:
  - type: worker
    name: ringba-csv-exporter
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python src/simple_export.py
    plan: starter
    branch: main
    numInstances: 1
    autoDeploy: true
    envVars:
      - key: RINGBA_USERNAME
        sync: false
      - key: RINGBA_PASSWORD
        sync: false
      - key: RPC_THRESHOLD
        value: 10.0
      - key: USE_HEADLESS
        value: true
      - key: PYTHONUNBUFFERED
        value: true
      - key: MORNING_CHECK_TIME
        value: 10:00
      - key: AFTERNOON_CHECK_TIME
        value: 15:00
      - key: TZ
        value: America/New_York
    schedule: "0 10,15 * * *" # Runs at 10 AM and 3 PM in the TZ timezone 