services:
  - type: cron
    name: ringba-csv-exporter
    env: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    branch: main
    numInstances: 1
    autoDeploy: true
    envVars:
      - key: RINGBA_USERNAME
        sync: false
      - key: RINGBA_PASSWORD
        sync: false
      - key: RINGBA_API_TOKEN
        sync: false
      - key: RINGBA_ACCOUNT_ID
        sync: false
      - key: SLACK_WEBHOOK_URL
        sync: false
      - key: RPC_THRESHOLD
        value: 12.0
      - key: MORNING_CHECK_TIME
        value: 11:00
      - key: MIDDAY_CHECK_TIME
        value: 14:00
      - key: AFTERNOON_CHECK_TIME
        value: 16:30
      - key: TZ
        value: America/New_York
    # Schedule for 11 AM ET
    schedule: "0 15 * * *"
    # Extra schedules for 2 PM and 4:30 PM ET
    extraSchedules:
      - cron: "0 18 * * *"  # 2 PM ET (18:00 UTC)
      - cron: "30 20 * * *"  # 4:30 PM ET (20:30 UTC) 