services:
  - type: web
    name: ringba-exporter
    env: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    branch: main
    numInstances: 1
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: RINGBA_USERNAME
        sync: false
      - key: RINGBA_PASSWORD
        sync: false
      - key: RINGBA_API_TOKEN
        sync: false
      - key: RINGBA_ACCOUNT_ID
        sync: false
      - key: SLACK_WEBHOOK_URL
        sync: false
      - key: RPC_THRESHOLD
        value: 12.0
      - key: MORNING_CHECK_TIME
        value: 11:00
      - key: MIDDAY_CHECK_TIME
        value: 14:00
      - key: AFTERNOON_CHECK_TIME
        value: 16:30
      - key: TZ
        value: America/New_York
      - key: PYTHONUNBUFFERED
        value: "true"
      - key: USE_HEADLESS
        value: "true"
      - key: CHROME_OPTIONS
        value: "--headless=new --no-sandbox --disable-dev-shm-usage --disable-gpu --disable-software-rasterizer --disable-extensions" 