services:
  - type: cron
    name: ringba-csv-exporter
    env: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    branch: main
    numInstances: 1
    autoDeploy: true
    envVars:
      - key: RINGBA_USERNAME
        sync: false
      - key: RINGBA_PASSWORD
        sync: false
      - key: RPC_THRESHOLD
        value: 10.0
      - key: MORNING_CHECK_TIME
        value: 10:00
      - key: AFTERNOON_CHECK_TIME
        value: 15:00
      - key: TZ
        value: America/New_York
      - key: SLACK_WEBHOOK_URL
        sync: false
    schedule: 0 10,15 * * *