services:
  # Background Worker Service
  - type: worker
    name: ringba-export-service
    env: python
    buildCommand: |
      chmod +x ./setup_chrome.sh
      ./setup_chrome.sh
      pip install -r requirements.txt
    startCommand: python src/simple_export.py
    runtime: python3.9
    plan: starter
    branch: main
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: CHROME_OPTIONS
        value: "--headless=new --no-sandbox --disable-dev-shm-usage --disable-gpu --single-process --disable-extensions"
      - key: SHM_SIZE
        value: "2g"
      - key: NODE_OPTIONS
        value: "--max-old-space-size=2048"
      - key: PATH
        value: "$HOME/bin:$PATH"
      - key: RPC_THRESHOLD
        value: "12.0"
      - key: MORNING_CHECK_TIME
        value: "11:00"
      - key: MIDDAY_CHECK_TIME
        value: "14:00"
      - key: AFTERNOON_CHECK_TIME
        value: "16:30"
      - key: TZ
        value: "America/New_York"
      # Add these from Render Dashboard:
      # - key: RINGBA_USERNAME
      #   sync: false
      # - key: RINGBA_PASSWORD
      #   sync: false
      # - key: SLACK_WEBHOOK_URL
      #   sync: false

  # Morning Cron Job
  - type: cron
    name: ringba-csv-exporter-morning
    env: python
    buildCommand: |
      chmod +x ./setup_chrome.sh
      ./setup_chrome.sh
      pip install -r requirements.txt
    startCommand: python src/simple_export.py
    schedule: "0 11 * * 1-5"
    runtime: python3.9
    plan: starter
    branch: main
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: CHROME_OPTIONS
        value: "--headless=new --no-sandbox --disable-dev-shm-usage --disable-gpu --single-process --disable-extensions"
      - key: PATH
        value: "$HOME/bin:$PATH"
      - key: RPC_THRESHOLD
        value: "12.0"
      - key: RUN_LABEL
        value: "morning"
      - key: TZ
        value: "America/New_York"
      # Add these from Render Dashboard
      # - key: RINGBA_USERNAME
      #   sync: false
      # - key: RINGBA_PASSWORD
      #   sync: false
      # - key: SLACK_WEBHOOK_URL
      #   sync: false

  # Midday Cron Job
  - type: cron
    name: ringba-csv-exporter-midday
    env: python
    buildCommand: |
      chmod +x ./setup_chrome.sh
      ./setup_chrome.sh
      pip install -r requirements.txt
    startCommand: python src/simple_export.py
    schedule: "0 14 * * 1-5"
    runtime: python3.9
    plan: starter
    branch: main
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: CHROME_OPTIONS
        value: "--headless=new --no-sandbox --disable-dev-shm-usage --disable-gpu --single-process --disable-extensions"
      - key: PATH
        value: "$HOME/bin:$PATH"
      - key: RPC_THRESHOLD
        value: "12.0"
      - key: RUN_LABEL
        value: "midday"
      - key: TZ
        value: "America/New_York"
      # Add these from Render Dashboard
      # - key: RINGBA_USERNAME
      #   sync: false
      # - key: RINGBA_PASSWORD
      #   sync: false
      # - key: SLACK_WEBHOOK_URL
      #   sync: false

  # Afternoon Cron Job
  - type: cron
    name: ringba-csv-exporter-afternoon
    env: python
    buildCommand: |
      chmod +x ./setup_chrome.sh
      ./setup_chrome.sh
      pip install -r requirements.txt
    startCommand: python src/simple_export.py
    schedule: "30 16 * * 1-5"
    runtime: python3.9
    plan: starter
    branch: main
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: CHROME_OPTIONS
        value: "--headless=new --no-sandbox --disable-dev-shm-usage --disable-gpu --single-process --disable-extensions"
      - key: PATH
        value: "$HOME/bin:$PATH"
      - key: RPC_THRESHOLD
        value: "12.0"
      - key: RUN_LABEL
        value: "afternoon"
      - key: TZ
        value: "America/New_York"
      # Add these from Render Dashboard
      # - key: RINGBA_USERNAME
      #   sync: false
      # - key: RINGBA_PASSWORD
      #   sync: false
      # - key: SLACK_WEBHOOK_URL
      #   sync: false 