services:
  - type: web
    name: ringba-export
    env: python
    buildCommand: |
      # Install Chrome and ChromeDriver dependencies
      apt-get update && apt-get install -y \
        wget \
        gnupg \
        unzip \
        xvfb \
        libxi6 \
        default-jdk \
        fonts-liberation \
        libasound2 \
        libatk-bridge2.0-0 \
        libatk1.0-0 \
        libcups2 \
        libdbus-1-3 \
        libgdk-pixbuf2.0-0 \
        libgtk-3-0 \
        libnspr4 \
        libnss3 \
        libx11-xcb1 \
        libxcomposite1 \
        libxcursor1 \
        libxdamage1 \
        libxfixes3 \
        libxrandr2 \
        libxrender1 \
        libxss1 \
        libxtst6 \
        xdg-utils
      
      # Install Chrome
      wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
      echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list
      apt-get update
      apt-get install -y google-chrome-stable
      
      # Install ChromeDriver using a more direct approach
      # Get the Chrome version
      CHROME_VERSION=$(google-chrome --version | awk '{print $3}' | cut -d. -f1)
      echo "Chrome version: $CHROME_VERSION"
      
      # Download the matching ChromeDriver version
      wget -q -O /tmp/LATEST_RELEASE "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION"
      DRIVER_VERSION=$(cat /tmp/LATEST_RELEASE)
      echo "Using ChromeDriver version: $DRIVER_VERSION"
      
      # Download and install ChromeDriver
      wget -q -O /tmp/chromedriver.zip "https://chromedriver.storage.googleapis.com/$DRIVER_VERSION/chromedriver_linux64.zip"
      unzip -o /tmp/chromedriver.zip -d /usr/local/bin/
      chmod +x /usr/local/bin/chromedriver
      
      # Create symlinks to ensure it's in PATH
      ln -sf /usr/local/bin/chromedriver /usr/bin/chromedriver
      
      # Verify installations and permissions
      echo "Checking installations:"
      google-chrome --version
      chromedriver --version
      ls -la /usr/local/bin/chromedriver
      ls -la /usr/bin/chromedriver
      echo "PATH: $PATH"
      
      # Install Python dependencies
      pip install -r requirements.txt
    startCommand: python src/web_service.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: RINGBA_USERNAME
        sync: false
      - key: RINGBA_PASSWORD
        sync: false
      - key: SLACK_WEBHOOK_URL
        sync: false
      - key: RINGBA_API_TOKEN
        sync: false
      - key: RINGBA_ACCOUNT_ID
        sync: false
      - key: RPC_THRESHOLD
        value: 12.0
      - key: MORNING_CHECK_TIME
        value: 11:00
      - key: MIDDAY_CHECK_TIME
        value: 14:00
      - key: AFTERNOON_CHECK_TIME
        value: 16:30
      - key: TZ
        value: America/New_York
      - key: USE_HEADLESS
        value: true
      - key: CHROME_OPTIONS
        value: "--headless=new --no-sandbox --disable-dev-shm-usage --disable-gpu --disable-software-rasterizer --disable-extensions"
      - key: PYTHONUNBUFFERED
        value: true
      - key: PATH
        value: "/usr/local/bin:/usr/bin:${PATH}"
      - key: PORT
        value: 8080 